# -*- coding: utf-8 -*-
"""1393_249_949

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19eXVaZsLkgkAqrqeqYsa8DL1KAXlE7I3
"""

import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

data = pd.read_csv('/content/calories_burned_data.csv')

data.head(3)

data = pd.get_dummies(data, columns=["Gender"], drop_first = True)

y = data[["Calories Burned"]]
x = data.drop("Calories Burned", axis=1)

x_train, x_test, y_train, y_test = train_test_split(x, y, train_size=0.70, random_state=22)

lm = LinearRegression()
model = lm.fit(x_train, y_train)
model.score(x_test, y_test)

data.head(3)

model.predict([[18,182,65,20.1,60,9.5,3.00,140,True]])